name: Build and Push Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/backend/**'
      - 'Dockerfile'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image (CI Validation)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false  # Chuyển thành false để không cần đẩy lên mạng
          tags: test-backend:latest
